import type { WordEntry } from "../types.js";

/**
 * Animals, 200 entries: 70 at level 1, 90 at level 2, 40 at level 3.
 * Living creatures only — hints describe form, colour, habitat, sound and
 * movement, never the identity and never the category. Raw animal names are
 * claimed here (Duck, Chicken, Crab, Lobster, Salmon, Tuna, Squid, Fish, Dog);
 * prepared forms stay with Food & Drink, products stay with Objects. "Lamb" is
 * deliberately dropped in favour of "Sheep" to avoid a confusable pair.
 */
export const animals: readonly WordEntry[] = [
  // level 1 — universally known
  { word: "Dog", hint: "loyal, domestic, vocal", level: 1 },
  { word: "Cat", hint: "soft, aloof, purring", level: 1 },
  { word: "Horse", hint: "tall, ridden, hooved", level: 1 },
  { word: "Cow", hint: "large, grazing, milked daily", level: 1 },
  { word: "Pig", hint: "snouted, muddy, curly tail", level: 1 },
  { word: "Sheep", hint: "woolly, flocking, timid", level: 1 },
  { word: "Goat", hint: "horned, agile, chews anything", level: 1 },
  { word: "Chicken", hint: "feathered, clucking, farmyard", level: 1 },
  { word: "Duck", hint: "webbed feet, quacking, floats", level: 1 },
  { word: "Lion", hint: "golden, maned, roaring", level: 1 },
  { word: "Tiger", hint: "striped, orange, stalking", level: 1 },
  { word: "Elephant", hint: "grey, huge, long trunk", level: 1 },
  { word: "Giraffe", hint: "towering, spotted, very long neck", level: 1 },
  { word: "Monkey", hint: "nimble, climbing, mischievous", level: 1 },
  { word: "Bear", hint: "heavy, furred, sleeps all winter", level: 1 },
  { word: "Wolf", hint: "grey, howling, hunts in packs", level: 1 },
  { word: "Fox", hint: "red, cunning, bushy tail", level: 1 },
  { word: "Rabbit", hint: "long ears, hopping, burrows", level: 1 },
  { word: "Mouse", hint: "tiny, grey, nibbles quietly", level: 1 },
  { word: "Rat", hint: "long-tailed, urban, quick", level: 1 },
  { word: "Snake", hint: "legless, scaled, hissing", level: 1 },
  { word: "Frog", hint: "green, hopping, croaking", level: 1 },
  { word: "Fish", hint: "silver, scaled, glides underwater", level: 1 },
  { word: "Shark", hint: "grey fin, feared, ocean hunter", level: 1 },
  { word: "Whale", hint: "enormous, spouting, deep ocean", level: 1 },
  { word: "Dolphin", hint: "sleek, playful, leaps from water", level: 1 },
  { word: "Eagle", hint: "sharp-eyed, soaring, hooked beak", level: 1 },
  { word: "Owl", hint: "round-eyed, nocturnal, silent flight", level: 1 },
  { word: "Penguin", hint: "upright, waddling, very cold", level: 1 },
  { word: "Bee", hint: "yellow stripes, buzzing, makes honey", level: 1 },
  { word: "Ant", hint: "tiny, underground, marches in lines", level: 1 },
  { word: "Spider", hint: "eight legs, weaves, scuttling", level: 1 },
  { word: "Butterfly", hint: "bright wings, delicate, drifting", level: 1 },
  { word: "Snail", hint: "slow, shelled, leaves a trail", level: 1 },
  { word: "Turtle", hint: "armoured, slow, ancient", level: 1 },
  { word: "Crocodile", hint: "long jaws, lurking, river banks", level: 1 },
  { word: "Lizard", hint: "small, scaly, sun-warmed", level: 1 },
  { word: "Goldfish", hint: "orange, circling, kept in glass", level: 1 },
  { word: "Hamster", hint: "small, furry, spins a wheel", level: 1 },
  { word: "Parrot", hint: "colourful, perched, mimics speech", level: 1 },
  { word: "Pigeon", hint: "grey, pecking, city squares", level: 1 },
  { word: "Crow", hint: "black, cawing, clever", level: 1 },
  { word: "Seagull", hint: "white, coastal, screeching", level: 1 },
  { word: "Swan", hint: "white, long neck, glides", level: 1 },
  { word: "Peacock", hint: "fanned tail, iridescent, strutting", level: 1 },
  { word: "Camel", hint: "humped, desert, long trek", level: 1 },
  { word: "Kangaroo", hint: "bounding, pouched, powerful legs", level: 1 },
  { word: "Zebra", hint: "striped, black and white, grazing", level: 1 },
  { word: "Gorilla", hint: "huge, dark, beats its chest", level: 1 },
  { word: "Panda", hint: "round, bamboo, dark eye patches", level: 1 },
  { word: "Deer", hint: "graceful, antlered, forest edges", level: 1 },
  { word: "Squirrel", hint: "bushy tail, hoards nuts, climbs", level: 1 },
  { word: "Bat", hint: "leathery wings, hangs upside down", level: 1 },
  { word: "Worm", hint: "soft, segmented, lives in soil", level: 1 },
  { word: "Fly", hint: "buzzing, quick, lands on food", level: 1 },
  { word: "Mosquito", hint: "tiny, whining, itchy bites", level: 1 },
  { word: "Goose", hint: "honking, long neck, aggressive", level: 1 },
  { word: "Turkey", hint: "plump, wattled, gobbling", level: 1 },
  { word: "Donkey", hint: "stubborn, grey, braying", level: 1 },
  { word: "Bull", hint: "heavy, horned, charging", level: 1 },
  { word: "Crab", hint: "sideways, clawed, hard shell", level: 1 },
  { word: "Lobster", hint: "clawed, armoured, ocean floor", level: 1 },
  { word: "Octopus", hint: "many-limbed, clever, marine", level: 1 },
  { word: "Jellyfish", hint: "transparent, drifting, stinging", level: 1 },
  { word: "Starfish", hint: "five arms, rock pools, clinging", level: 1 },
  { word: "Salmon", hint: "pink, silver-scaled, leaps upstream", level: 1 },
  { word: "Tuna", hint: "large, silver, deep water", level: 1 },
  { word: "Seal", hint: "sleek, barking, coastal rocks", level: 1 },
  { word: "Ostrich", hint: "flightless, long legs, very fast", level: 1 },
  { word: "Flamingo", hint: "pink, one-legged, wading", level: 1 },
  // level 2 — commonly known
  { word: "Dove", hint: "white, cooing, gentle", level: 2 },
  { word: "Sparrow", hint: "small, brown, hops in hedges", level: 2 },
  { word: "Robin", hint: "small, red breast, garden visitor", level: 2 },
  { word: "Caterpillar", hint: "many-legged, striped, chews leaves", level: 2 },
  { word: "Ladybird", hint: "red domed shell, black spots", level: 2 },
  { word: "Hippopotamus", hint: "vast, grey, wallows in rivers", level: 2 },
  { word: "Rhinoceros", hint: "armour-plated, horned, heavy charge", level: 2 },
  { word: "Cheetah", hint: "spotted, fastest sprinter, lean", level: 2 },
  { word: "Leopard", hint: "dappled coat, solitary, climbs trees", level: 2 },
  { word: "Hyena", hint: "laughing call, scruffy, scavenger", level: 2 },
  { word: "Otter", hint: "playful, sleek, river banks", level: 2 },
  { word: "Beaver", hint: "flat tail, gnaws timber, dams", level: 2 },
  { word: "Badger", hint: "striped face, digs setts, nocturnal", level: 2 },
  { word: "Hedgehog", hint: "spined, curls into a ball", level: 2 },
  { word: "Mole", hint: "blind, tunnels, pushes up soil", level: 2 },
  { word: "Weasel", hint: "long, thin, quick and sly", level: 2 },
  { word: "Ferret", hint: "slender, curious, endlessly wriggling", level: 2 },
  { word: "Skunk", hint: "black stripe, foul spray", level: 2 },
  { word: "Raccoon", hint: "masked face, nimble paws, thieving", level: 2 },
  { word: "Koala", hint: "grey, sleepy, clings to branches", level: 2 },
  { word: "Sloth", hint: "unhurried, shaggy, hangs from branches", level: 2 },
  { word: "Armadillo", hint: "banded shell, rolls up, digs", level: 2 },
  { word: "Anteater", hint: "long snout, sticky tongue, digging", level: 2 },
  { word: "Porcupine", hint: "bristling quills, slow, defensive", level: 2 },
  { word: "Chipmunk", hint: "striped back, cheeks full, tiny", level: 2 },
  { word: "Bison", hint: "shaggy, massive shoulders, plains", level: 2 },
  { word: "Moose", hint: "broad antlers, gangling, northern forests", level: 2 },
  { word: "Antelope", hint: "graceful, horned, leaping over plains", level: 2 },
  { word: "Gazelle", hint: "slender, bounding, dry grassland", level: 2 },
  { word: "Llama", hint: "long-necked, woolly, pack carrier", level: 2 },
  { word: "Yak", hint: "shaggy, high mountains, heavy coat", level: 2 },
  { word: "Walrus", hint: "tusked, blubbery, cold shores", level: 2 },
  { word: "Manatee", hint: "bulky, gentle, drifts in shallows", level: 2 },
  { word: "Stingray", hint: "flat, gliding, whip tail", level: 2 },
  { word: "Swordfish", hint: "long pointed bill, fast swimmer", level: 2 },
  { word: "Seahorse", hint: "tiny, curled tail, upright swimmer", level: 2 },
  { word: "Squid", hint: "long tentacles, inky, deep water", level: 2 },
  { word: "Oyster", hint: "rough shell, briny, prised open", level: 2 },
  { word: "Mussel", hint: "blue-black, clustered on rocks", level: 2 },
  { word: "Trout", hint: "speckled, freshwater, quick in streams", level: 2 },
  { word: "Sardine", hint: "small, oily, packed tightly", level: 2 },
  { word: "Eel", hint: "long, slippery, hides in mud", level: 2 },
  { word: "Piranha", hint: "sharp teeth, swarming, river shallows", level: 2 },
  { word: "Catfish", hint: "whiskered, bottom-dwelling, muddy river", level: 2 },
  { word: "Newt", hint: "small, damp, orange belly", level: 2 },
  { word: "Salamander", hint: "damp, dark, slips under logs", level: 2 },
  { word: "Gecko", hint: "sticky toes, clings to walls", level: 2 },
  { word: "Iguana", hint: "spiny crest, green, basking", level: 2 },
  { word: "Chameleon", hint: "colour-changing, bulging eyes, slow", level: 2 },
  { word: "Cobra", hint: "hooded, upright, venomous strike", level: 2 },
  { word: "Python", hint: "thick coils, crushing, tropical", level: 2 },
  { word: "Falcon", hint: "swift, hooked beak, dives fast", level: 2 },
  { word: "Vulture", hint: "bald head, circling, waits", level: 2 },
  { word: "Magpie", hint: "black and white, chattering, thieving", level: 2 },
  { word: "Woodpecker", hint: "drilling, tree trunks, red cap", level: 2 },
  { word: "Kingfisher", hint: "bright blue, darts over rivers", level: 2 },
  { word: "Heron", hint: "long legs, still, patient wader", level: 2 },
  { word: "Stork", hint: "long bill, white, tall nest", level: 2 },
  { word: "Pelican", hint: "big pouch under its beak", level: 2 },
  { word: "Albatross", hint: "vast wingspan, ocean glider, rare", level: 2 },
  { word: "Puffin", hint: "stout, striped beak, cliff burrows", level: 2 },
  { word: "Toucan", hint: "enormous colourful beak, tropical", level: 2 },
  { word: "Canary", hint: "small, yellow, sings brightly", level: 2 },
  { word: "Nightingale", hint: "plain brown, sings after dark", level: 2 },
  { word: "Cuckoo", hint: "repeating call, lays elsewhere, grey", level: 2 },
  { word: "Swallow", hint: "forked tail, darting, migrates far", level: 2 },
  { word: "Wren", hint: "tiny, brown, surprisingly loud", level: 2 },
  { word: "Blackbird", hint: "dark, orange beak, garden singer", level: 2 },
  { word: "Finch", hint: "small, seed-cracking beak, colourful", level: 2 },
  { word: "Quail", hint: "plump, ground-dwelling, bursts upward", level: 2 },
  { word: "Pheasant", hint: "bronze, long tail, ground-nesting", level: 2 },
  { word: "Wasp", hint: "narrow waist, yellow, aggressive sting", level: 2 },
  { word: "Dragonfly", hint: "long body, glassy wings, hovering", level: 2 },
  { word: "Grasshopper", hint: "green, springs from stems, chirping", level: 2 },
  { word: "Cricket", hint: "nocturnal, small, rubs its legs", level: 2 },
  { word: "Beetle", hint: "hard-shelled, glossy, six legs", level: 2 },
  { word: "Moth", hint: "dull wings, drawn to lamps", level: 2 },
  { word: "Cockroach", hint: "flat, scuttling, hides in cracks", level: 2 },
  { word: "Termite", hint: "chews timber, builds tall mounds", level: 2 },
  { word: "Flea", hint: "minute, jumping, irritating bite", level: 2 },
  { word: "Scorpion", hint: "curved sting, armoured, desert", level: 2 },
  { word: "Centipede", hint: "many legs, flat, fast under stones", level: 2 },
  { word: "Firefly", hint: "glowing at dusk, drifting light", level: 2 },
  { word: "Locust", hint: "swarming, devours crops, plague", level: 2 },
  { word: "Tarantula", hint: "hairy, large, eight slow legs", level: 2 },
  { word: "Chimpanzee", hint: "clever, social, walks on knuckles", level: 2 },
  { word: "Baboon", hint: "pink rump, troop, bared teeth", level: 2 },
  { word: "Orangutan", hint: "red-haired, long arms, treetops", level: 2 },
  { word: "Lemur", hint: "ringed tail, big eyes, leaping", level: 2 },
  { word: "Meerkat", hint: "upright, alert, desert burrows", level: 2 },
  // level 3 — niche, opt-in
  { word: "Pangolin", hint: "armour-plated, curls up tight", level: 3 },
  { word: "Aardvark", hint: "pale, tubular snout, nocturnal digger", level: 3 },
  { word: "Okapi", hint: "striped legs, forest, secretive", level: 3 },
  { word: "Tapir", hint: "snuffling snout, stocky, rainforest", level: 3 },
  { word: "Capybara", hint: "huge rodent, calm, riverside", level: 3 },
  { word: "Wombat", hint: "stout, burrowing, blunt-faced", level: 3 },
  { word: "Echidna", hint: "spined, snouted, egg-laying", level: 3 },
  { word: "Platypus", hint: "duck-billed, swims, lays eggs", level: 3 },
  { word: "Quokka", hint: "small, grinning, island-dwelling", level: 3 },
  { word: "Marmoset", hint: "tiny, tufted ears, tree-dwelling", level: 3 },
  { word: "Lynx", hint: "short tail, silent, snow-padded paws", level: 3 },
  { word: "Ocelot", hint: "small, spotted, night-prowling", level: 3 },
  { word: "Wolverine", hint: "stocky, ferocious, snowy north", level: 3 },
  { word: "Ibex", hint: "curved horns, cliffs, sure-footed", level: 3 },
  { word: "Oryx", hint: "straight horns, pale, desert herd", level: 3 },
  { word: "Gibbon", hint: "long arms, swinging, loud calls", level: 3 },
  { word: "Bonobo", hint: "peaceful, social, shares food", level: 3 },
  { word: "Mandrill", hint: "bright blue face, forest floor", level: 3 },
  { word: "Narwhal", hint: "single spiral tusk, arctic", level: 3 },
  { word: "Beluga", hint: "white, rounded head, arctic waters", level: 3 },
  { word: "Dugong", hint: "slow grazer, shallow warm seas", level: 3 },
  {
    word: "Coelacanth",
    hint: "deep-dwelling, thought extinct, ancient",
    level: 3,
  },
  { word: "Sturgeon", hint: "huge, bony plates, slow river", level: 3 },
  { word: "Barracuda", hint: "long, silver, rows of teeth", level: 3 },
  { word: "Cuttlefish", hint: "colour-shifting, flat, drifting arms", level: 3 },
  { word: "Nautilus", hint: "coiled shell, chambered, deep", level: 3 },
  { word: "Barnacle", hint: "crusted, immobile, ship hulls", level: 3 },
  { word: "Axolotl", hint: "pink, frilled gills, permanently young", level: 3 },
  {
    word: "Komodo Dragon",
    hint: "giant lizard, heavy, island predator",
    level: 3,
  },
  { word: "Tuatara", hint: "spiny crest, sluggish, long-lived", level: 3 },
  { word: "Kakapo", hint: "flightless, green, ground-nesting", level: 3 },
  { word: "Osprey", hint: "hooked talons, plunges from height", level: 3 },
  { word: "Condor", hint: "vast wings, bald head, mountains", level: 3 },
  { word: "Ibis", hint: "curved bill, long legs, wading", level: 3 },
  { word: "Cassowary", hint: "towering, flightless, vivid blue neck", level: 3 },
  { word: "Kookaburra", hint: "laughing call, stout beak, perched", level: 3 },
  { word: "Lyrebird", hint: "mimics any sound, long tail", level: 3 },
  { word: "Praying Mantis", hint: "folded forelimbs, still, green", level: 3 },
  { word: "Cicada", hint: "shrill drone, emerges in summer", level: 3 },
  { word: "Mongoose", hint: "quick, slender, fights snakes", level: 3 },
];
