import type { WordEntry } from "../types.js";

/**
 * Animals, 200 entries: 70 at level 1, 90 at level 2, 40 at level 3.
 *
 * Every hint is exactly one lowercase word — no phrases, no commas, no
 * hyphens. One word keeps the imposter's reveal layout-identical to a crew
 * reveal, so the two cards cannot be told apart across the table. Each hint
 * names a single property (form, colour, habitat, sound, movement, mood) that
 * narrows the domain without naming the identity, and shares no stem with its
 * own word in either direction — Seahorse is never "equine", Hedgehog never
 * "hoggish", Starfish never "starry". Hints are unique within this file; they
 * may repeat across other categories.
 *
 * Living creatures only. Raw animal names are claimed here (Duck, Chicken,
 * Crab, Lobster, Salmon, Tuna, Squid, Fish, Dog); prepared forms stay with
 * Food & Drink, products stay with Objects. "Lamb" is deliberately dropped in
 * favour of "Sheep" to avoid a confusable pair.
 */
export const animals: readonly WordEntry[] = [
  // level 1 — universally known
  { word: "Dog", hint: "loyal", level: 1 },
  { word: "Cat", hint: "aloof", level: 1 },
  { word: "Horse", hint: "ridden", level: 1 },
  { word: "Cow", hint: "grazing", level: 1 },
  { word: "Pig", hint: "muddy", level: 1 },
  { word: "Sheep", hint: "docile", level: 1 },
  { word: "Goat", hint: "clambering", level: 1 },
  { word: "Chicken", hint: "scratching", level: 1 },
  { word: "Duck", hint: "paddling", level: 1 },
  { word: "Lion", hint: "regal", level: 1 },
  { word: "Tiger", hint: "striped", level: 1 },
  { word: "Elephant", hint: "colossal", level: 1 },
  { word: "Giraffe", hint: "towering", level: 1 },
  { word: "Monkey", hint: "mischievous", level: 1 },
  { word: "Bear", hint: "hibernating", level: 1 },
  { word: "Wolf", hint: "howling", level: 1 },
  { word: "Fox", hint: "cunning", level: 1 },
  { word: "Rabbit", hint: "hopping", level: 1 },
  { word: "Mouse", hint: "nibbling", level: 1 },
  { word: "Rat", hint: "scurrying", level: 1 },
  { word: "Snake", hint: "hissing", level: 1 },
  { word: "Frog", hint: "croaking", level: 1 },
  { word: "Fish", hint: "finned", level: 1 },
  { word: "Shark", hint: "feared", level: 1 },
  { word: "Whale", hint: "enormous", level: 1 },
  { word: "Dolphin", hint: "playful", level: 1 },
  { word: "Eagle", hint: "soaring", level: 1 },
  { word: "Owl", hint: "nocturnal", level: 1 },
  { word: "Penguin", hint: "waddling", level: 1 },
  { word: "Bee", hint: "buzzing", level: 1 },
  { word: "Ant", hint: "marching", level: 1 },
  { word: "Spider", hint: "weaving", level: 1 },
  { word: "Butterfly", hint: "drifting", level: 1 },
  { word: "Snail", hint: "trailing", level: 1 },
  { word: "Turtle", hint: "armoured", level: 1 },
  { word: "Crocodile", hint: "lurking", level: 1 },
  { word: "Lizard", hint: "scaly", level: 1 },
  { word: "Goldfish", hint: "circling", level: 1 },
  { word: "Hamster", hint: "caged", level: 1 },
  { word: "Parrot", hint: "mimicking", level: 1 },
  { word: "Pigeon", hint: "pecking", level: 1 },
  { word: "Crow", hint: "ominous", level: 1 },
  { word: "Seagull", hint: "screeching", level: 1 },
  { word: "Swan", hint: "gliding", level: 1 },
  { word: "Peacock", hint: "iridescent", level: 1 },
  { word: "Camel", hint: "plodding", level: 1 },
  { word: "Kangaroo", hint: "bounding", level: 1 },
  { word: "Zebra", hint: "monochrome", level: 1 },
  { word: "Gorilla", hint: "massive", level: 1 },
  { word: "Panda", hint: "patched", level: 1 },
  { word: "Deer", hint: "startled", level: 1 },
  { word: "Squirrel", hint: "hoarding", level: 1 },
  { word: "Bat", hint: "leathery", level: 1 },
  { word: "Worm", hint: "segmented", level: 1 },
  { word: "Fly", hint: "pestering", level: 1 },
  { word: "Mosquito", hint: "whining", level: 1 },
  { word: "Goose", hint: "honking", level: 1 },
  { word: "Turkey", hint: "strutting", level: 1 },
  { word: "Donkey", hint: "stubborn", level: 1 },
  { word: "Bull", hint: "charging", level: 1 },
  { word: "Crab", hint: "scuttling", level: 1 },
  { word: "Lobster", hint: "clawed", level: 1 },
  { word: "Octopus", hint: "tentacled", level: 1 },
  { word: "Jellyfish", hint: "translucent", level: 1 },
  { word: "Starfish", hint: "radial", level: 1 },
  { word: "Salmon", hint: "upstream", level: 1 },
  { word: "Tuna", hint: "silvery", level: 1 },
  { word: "Seal", hint: "barking", level: 1 },
  { word: "Ostrich", hint: "flightless", level: 1 },
  { word: "Flamingo", hint: "pink", level: 1 },
  // level 2 — commonly known
  { word: "Dove", hint: "cooing", level: 2 },
  { word: "Sparrow", hint: "hedgerow", level: 2 },
  { word: "Robin", hint: "territorial", level: 2 },
  { word: "Caterpillar", hint: "munching", level: 2 },
  { word: "Ladybird", hint: "spotted", level: 2 },
  { word: "Hippopotamus", hint: "wallowing", level: 2 },
  { word: "Rhinoceros", hint: "horned", level: 2 },
  { word: "Cheetah", hint: "sprinting", level: 2 },
  { word: "Leopard", hint: "dappled", level: 2 },
  { word: "Hyena", hint: "cackling", level: 2 },
  { word: "Otter", hint: "frolicking", level: 2 },
  { word: "Beaver", hint: "industrious", level: 2 },
  { word: "Badger", hint: "burrowing", level: 2 },
  { word: "Hedgehog", hint: "prickly", level: 2 },
  { word: "Mole", hint: "tunnelling", level: 2 },
  { word: "Weasel", hint: "sinuous", level: 2 },
  { word: "Ferret", hint: "wriggling", level: 2 },
  { word: "Skunk", hint: "unwelcome", level: 2 },
  { word: "Raccoon", hint: "masked", level: 2 },
  { word: "Koala", hint: "drowsy", level: 2 },
  { word: "Sloth", hint: "unhurried", level: 2 },
  { word: "Armadillo", hint: "banded", level: 2 },
  { word: "Anteater", hint: "snouted", level: 2 },
  { word: "Porcupine", hint: "quilled", level: 2 },
  { word: "Chipmunk", hint: "pouched", level: 2 },
  { word: "Bison", hint: "thundering", level: 2 },
  { word: "Moose", hint: "gangling", level: 2 },
  { word: "Antelope", hint: "leaping", level: 2 },
  { word: "Gazelle", hint: "skittish", level: 2 },
  { word: "Llama", hint: "fleecy", level: 2 },
  { word: "Yak", hint: "shaggy", level: 2 },
  { word: "Walrus", hint: "tusked", level: 2 },
  { word: "Manatee", hint: "lumbering", level: 2 },
  { word: "Stingray", hint: "flattened", level: 2 },
  { word: "Swordfish", hint: "streamlined", level: 2 },
  { word: "Seahorse", hint: "curled", level: 2 },
  { word: "Squid", hint: "inky", level: 2 },
  { word: "Oyster", hint: "prised", level: 2 },
  { word: "Mussel", hint: "clustered", level: 2 },
  { word: "Trout", hint: "speckled", level: 2 },
  { word: "Sardine", hint: "tinned", level: 2 },
  { word: "Eel", hint: "writhing", level: 2 },
  { word: "Piranha", hint: "frenzied", level: 2 },
  { word: "Catfish", hint: "whiskered", level: 2 },
  { word: "Newt", hint: "damp", level: 2 },
  { word: "Salamander", hint: "mottled", level: 2 },
  { word: "Gecko", hint: "clinging", level: 2 },
  { word: "Iguana", hint: "basking", level: 2 },
  { word: "Chameleon", hint: "shifting", level: 2 },
  { word: "Cobra", hint: "venomous", level: 2 },
  { word: "Python", hint: "constricting", level: 2 },
  { word: "Falcon", hint: "stooping", level: 2 },
  { word: "Vulture", hint: "patient", level: 2 },
  { word: "Magpie", hint: "chattering", level: 2 },
  { word: "Woodpecker", hint: "drumming", level: 2 },
  { word: "Kingfisher", hint: "darting", level: 2 },
  { word: "Heron", hint: "motionless", level: 2 },
  { word: "Stork", hint: "nesting", level: 2 },
  { word: "Pelican", hint: "capacious", level: 2 },
  { word: "Albatross", hint: "oceanic", level: 2 },
  { word: "Puffin", hint: "cliffside", level: 2 },
  { word: "Toucan", hint: "beaked", level: 2 },
  { word: "Canary", hint: "tuneful", level: 2 },
  { word: "Nightingale", hint: "melodious", level: 2 },
  { word: "Cuckoo", hint: "repetitive", level: 2 },
  { word: "Swallow", hint: "migrating", level: 2 },
  { word: "Wren", hint: "diminutive", level: 2 },
  { word: "Blackbird", hint: "warbling", level: 2 },
  { word: "Finch", hint: "flitting", level: 2 },
  { word: "Quail", hint: "plump", level: 2 },
  { word: "Pheasant", hint: "bronzed", level: 2 },
  { word: "Wasp", hint: "stinging", level: 2 },
  { word: "Dragonfly", hint: "hovering", level: 2 },
  { word: "Grasshopper", hint: "springing", level: 2 },
  { word: "Cricket", hint: "rasping", level: 2 },
  { word: "Beetle", hint: "glossy", level: 2 },
  { word: "Moth", hint: "dusty", level: 2 },
  { word: "Cockroach", hint: "skittering", level: 2 },
  { word: "Termite", hint: "infesting", level: 2 },
  { word: "Flea", hint: "itching", level: 2 },
  { word: "Scorpion", hint: "arid", level: 2 },
  { word: "Centipede", hint: "creeping", level: 2 },
  { word: "Firefly", hint: "glowing", level: 2 },
  { word: "Locust", hint: "swarming", level: 2 },
  { word: "Tarantula", hint: "hairy", level: 2 },
  { word: "Chimpanzee", hint: "social", level: 2 },
  { word: "Baboon", hint: "quarrelsome", level: 2 },
  { word: "Orangutan", hint: "arboreal", level: 2 },
  { word: "Lemur", hint: "ringed", level: 2 },
  { word: "Meerkat", hint: "vigilant", level: 2 },
  // level 3 — niche, opt-in
  { word: "Pangolin", hint: "scaled", level: 3 },
  { word: "Aardvark", hint: "pallid", level: 3 },
  { word: "Okapi", hint: "secretive", level: 3 },
  { word: "Tapir", hint: "snuffling", level: 3 },
  { word: "Capybara", hint: "placid", level: 3 },
  { word: "Wombat", hint: "blunt", level: 3 },
  { word: "Echidna", hint: "spined", level: 3 },
  { word: "Platypus", hint: "improbable", level: 3 },
  { word: "Quokka", hint: "grinning", level: 3 },
  { word: "Marmoset", hint: "tufted", level: 3 },
  { word: "Lynx", hint: "silent", level: 3 },
  { word: "Ocelot", hint: "prowling", level: 3 },
  { word: "Wolverine", hint: "ferocious", level: 3 },
  { word: "Ibex", hint: "surefooted", level: 3 },
  { word: "Oryx", hint: "pale", level: 3 },
  { word: "Gibbon", hint: "swinging", level: 3 },
  { word: "Bonobo", hint: "peaceable", level: 3 },
  { word: "Mandrill", hint: "vivid", level: 3 },
  { word: "Narwhal", hint: "spiralled", level: 3 },
  { word: "Beluga", hint: "arctic", level: 3 },
  { word: "Dugong", hint: "torpid", level: 3 },
  { word: "Coelacanth", hint: "primordial", level: 3 },
  { word: "Sturgeon", hint: "bony", level: 3 },
  { word: "Barracuda", hint: "toothed", level: 3 },
  { word: "Cuttlefish", hint: "pulsing", level: 3 },
  { word: "Nautilus", hint: "ancient", level: 3 },
  { word: "Barnacle", hint: "encrusted", level: 3 },
  { word: "Axolotl", hint: "aquatic", level: 3 },
  { word: "Komodo Dragon", hint: "predatory", level: 3 },
  { word: "Tuatara", hint: "sluggish", level: 3 },
  { word: "Kakapo", hint: "grounded", level: 3 },
  { word: "Osprey", hint: "plunging", level: 3 },
  { word: "Condor", hint: "bald", level: 3 },
  { word: "Ibis", hint: "wading", level: 3 },
  { word: "Cassowary", hint: "imposing", level: 3 },
  { word: "Kookaburra", hint: "laughing", level: 3 },
  { word: "Lyrebird", hint: "imitative", level: 3 },
  { word: "Praying Mantis", hint: "poised", level: 3 },
  { word: "Cicada", hint: "shrill", level: 3 },
  { word: "Mongoose", hint: "fearless", level: 3 },
];
