import type { WordEntry } from "../types.js";

/**
 * Food & Drink, 200 entries: 70 at level 1, 90 at level 2, 40 at level 3.
 *
 * Every hint is exactly one lowercase word — no phrases, no commas, no
 * hyphens. One word keeps the imposter's reveal layout-identical to a crew
 * reveal, so the two cards cannot be told apart across the table. Each hint
 * names a single property (texture, temperature, colour, sound, handling) that
 * narrows the domain without naming the identity, and shares no stem with its
 * own word in either direction. Hints are unique within this file; they may
 * repeat across other categories.
 *
 * Raw animal names are left to the Animals category; the only claims here are
 * prepared items ("Bacon", "Fried Chicken", "Fish and Chips").
 */
export const foodAndDrink: readonly WordEntry[] = [
  // level 1 — universally known
  { word: "Pizza", hint: "shared", level: 1 },
  { word: "Burger", hint: "stacked", level: 1 },
  { word: "Chocolate", hint: "melting", level: 1 },
  { word: "Ice Cream", hint: "scooped", level: 1 },
  { word: "Bread", hint: "sliced", level: 1 },
  { word: "Cheese", hint: "aged", level: 1 },
  { word: "Rice", hint: "boiled", level: 1 },
  { word: "Spaghetti", hint: "twirled", level: 1 },
  { word: "Noodles", hint: "slurped", level: 1 },
  { word: "Coffee", hint: "bitter", level: 1 },
  { word: "Tea", hint: "steeped", level: 1 },
  { word: "Milk", hint: "poured", level: 1 },
  { word: "Egg", hint: "fragile", level: 1 },
  { word: "Apple", hint: "crisp", level: 1 },
  { word: "Banana", hint: "curved", level: 1 },
  { word: "Orange", hint: "segmented", level: 1 },
  { word: "Strawberry", hint: "seeded", level: 1 },
  { word: "Grape", hint: "clustered", level: 1 },
  { word: "Watermelon", hint: "enormous", level: 1 },
  { word: "Lemon", hint: "sour", level: 1 },
  { word: "Potato", hint: "earthy", level: 1 },
  { word: "Tomato", hint: "juicy", level: 1 },
  { word: "Carrot", hint: "crunchy", level: 1 },
  { word: "Onion", hint: "pungent", level: 1 },
  { word: "Salad", hint: "tossed", level: 1 },
  { word: "Soup", hint: "ladled", level: 1 },
  { word: "Sandwich", hint: "portable", level: 1 },
  { word: "Butter", hint: "greasy", level: 1 },
  { word: "Sugar", hint: "granular", level: 1 },
  { word: "Salt", hint: "sprinkled", level: 1 },
  { word: "Honey", hint: "viscous", level: 1 },
  { word: "Jam", hint: "preserved", level: 1 },
  { word: "Cake", hint: "celebratory", level: 1 },
  { word: "Cookie", hint: "crumbly", level: 1 },
  { word: "Doughnut", hint: "glazed", level: 1 },
  { word: "Pancake", hint: "flipped", level: 1 },
  { word: "Waffle", hint: "gridded", level: 1 },
  { word: "Popcorn", hint: "puffed", level: 1 },
  { word: "French Fries", hint: "salted", level: 1 },
  { word: "Ketchup", hint: "squeezed", level: 1 },
  { word: "Mustard", hint: "tangy", level: 1 },
  { word: "Mayonnaise", hint: "pale", level: 1 },
  { word: "Peanut Butter", hint: "claggy", level: 1 },
  { word: "Cereal", hint: "dry", level: 1 },
  { word: "Yogurt", hint: "cultured", level: 1 },
  { word: "Hot Dog", hint: "handheld", level: 1 },
  { word: "Taco", hint: "folded", level: 1 },
  { word: "Burrito", hint: "wrapped", level: 1 },
  { word: "Steak", hint: "seared", level: 1 },
  { word: "Bacon", hint: "smoky", level: 1 },
  { word: "Sausage", hint: "cylindrical", level: 1 },
  { word: "Ham", hint: "cured", level: 1 },
  { word: "Toast", hint: "browned", level: 1 },
  { word: "Juice", hint: "chilled", level: 1 },
  { word: "Soda", hint: "fizzy", level: 1 },
  { word: "Beer", hint: "foamy", level: 1 },
  { word: "Wine", hint: "bottled", level: 1 },
  { word: "Espresso", hint: "concentrated", level: 1 },
  { word: "Pie", hint: "filled", level: 1 },
  { word: "Cucumber", hint: "cool", level: 1 },
  { word: "Peas", hint: "tiny", level: 1 },
  { word: "Garlic", hint: "lingering", level: 1 },
  { word: "Pineapple", hint: "spiky", level: 1 },
  { word: "Mango", hint: "tropical", level: 1 },
  { word: "Peach", hint: "fuzzy", level: 1 },
  { word: "Cherry", hint: "glossy", level: 1 },
  { word: "Candy", hint: "sugary", level: 1 },
  { word: "Pumpkin", hint: "hollowed", level: 1 },
  { word: "Sushi", hint: "precise", level: 1 },
  { word: "Fried Chicken", hint: "unctuous", level: 1 },

  // level 2 — commonly known
  { word: "Muffin", hint: "domed", level: 2 },
  { word: "Croissant", hint: "flaky", level: 2 },
  { word: "Baguette", hint: "crusty", level: 2 },
  { word: "Bagel", hint: "chewy", level: 2 },
  { word: "Pretzel", hint: "knotted", level: 2 },
  { word: "Scone", hint: "floury", level: 2 },
  { word: "Brownie", hint: "dense", level: 2 },
  { word: "Toffee", hint: "sticky", level: 2 },
  { word: "Caramel", hint: "burnt", level: 2 },
  { word: "Meringue", hint: "airy", level: 2 },
  { word: "Tiramisu", hint: "dusted", level: 2 },
  { word: "Custard", hint: "thick", level: 2 },
  { word: "Crepe", hint: "thin", level: 2 },
  { word: "Churro", hint: "ridged", level: 2 },
  { word: "Marshmallow", hint: "squishy", level: 2 },
  { word: "Avocado", hint: "buttery", level: 2 },
  { word: "Coconut", hint: "hairy", level: 2 },
  { word: "Pear", hint: "grainy", level: 2 },
  { word: "Blueberry", hint: "dark", level: 2 },
  { word: "Raspberry", hint: "hollow", level: 2 },
  { word: "Lime", hint: "zesty", level: 2 },
  { word: "Plum", hint: "purple", level: 2 },
  { word: "Fig", hint: "jammy", level: 2 },
  { word: "Pomegranate", hint: "staining", level: 2 },
  { word: "Broccoli", hint: "steamed", level: 2 },
  { word: "Lettuce", hint: "leafy", level: 2 },
  { word: "Mushroom", hint: "foraged", level: 2 },
  { word: "Celery", hint: "stringy", level: 2 },
  { word: "Spinach", hint: "wilting", level: 2 },
  { word: "Asparagus", hint: "tender", level: 2 },
  { word: "Eggplant", hint: "spongy", level: 2 },
  { word: "Bell Pepper", hint: "waxy", level: 2 },
  { word: "Chilli", hint: "fiery", level: 2 },
  { word: "Beetroot", hint: "crimson", level: 2 },
  { word: "Almond", hint: "oval", level: 2 },
  { word: "Pistachio", hint: "shelled", level: 2 },
  { word: "Chickpeas", hint: "firm", level: 2 },
  { word: "Tofu", hint: "absorbent", level: 2 },
  { word: "Cappuccino", hint: "frothed", level: 2 },
  { word: "Latte", hint: "milky", level: 2 },
  { word: "Smoothie", hint: "blended", level: 2 },
  { word: "Cider", hint: "orchard", level: 2 },
  { word: "Champagne", hint: "effervescent", level: 2 },
  { word: "Whiskey", hint: "amber", level: 2 },
  { word: "Vodka", hint: "odourless", level: 2 },
  { word: "Rum", hint: "nautical", level: 2 },
  { word: "Gin", hint: "botanical", level: 2 },
  { word: "Tequila", hint: "harsh", level: 2 },
  { word: "Marmalade", hint: "bittersweet", level: 2 },
  { word: "Maple Syrup", hint: "treacly", level: 2 },
  { word: "Soy Sauce", hint: "salty", level: 2 },
  { word: "Vinegar", hint: "acrid", level: 2 },
  { word: "Olive", hint: "brined", level: 2 },
  { word: "Pickle", hint: "puckering", level: 2 },
  { word: "Cinnamon", hint: "warming", level: 2 },
  { word: "Vanilla", hint: "fragrant", level: 2 },
  { word: "Ginger", hint: "knobbly", level: 2 },
  { word: "Basil", hint: "aromatic", level: 2 },
  { word: "Mint", hint: "cooling", level: 2 },
  { word: "Pepperoni", hint: "oily", level: 2 },
  { word: "Chorizo", hint: "coarse", level: 2 },
  { word: "Meatball", hint: "rolled", level: 2 },
  { word: "Feta", hint: "crumbling", level: 2 },
  { word: "Mozzarella", hint: "stretchy", level: 2 },
  { word: "Parmesan", hint: "grated", level: 2 },
  { word: "Brie", hint: "oozing", level: 2 },
  { word: "Curry", hint: "spiced", level: 2 },
  { word: "Lasagna", hint: "layered", level: 2 },
  { word: "Ravioli", hint: "stuffed", level: 2 },
  { word: "Risotto", hint: "creamy", level: 2 },
  { word: "Carbonara", hint: "silky", level: 2 },
  { word: "Pesto", hint: "ground", level: 2 },
  { word: "Paella", hint: "communal", level: 2 },
  { word: "Ramen", hint: "steaming", level: 2 },
  { word: "Dumpling", hint: "pinched", level: 2 },
  { word: "Spring Roll", hint: "wound", level: 2 },
  { word: "Kebab", hint: "charred", level: 2 },
  { word: "Falafel", hint: "herby", level: 2 },
  { word: "Hummus", hint: "beige", level: 2 },
  { word: "Guacamole", hint: "mashed", level: 2 },
  { word: "Quesadilla", hint: "griddled", level: 2 },
  { word: "Nachos", hint: "piled", level: 2 },
  { word: "Pita", hint: "pocketed", level: 2 },
  { word: "Naan", hint: "blistered", level: 2 },
  { word: "Samosa", hint: "triangular", level: 2 },
  { word: "Tempura", hint: "weightless", level: 2 },
  { word: "Omelette", hint: "whisked", level: 2 },
  { word: "Fish and Chips", hint: "vinegary", level: 2 },
  { word: "Couscous", hint: "fluffy", level: 2 },
  { word: "Pad Thai", hint: "tangled", level: 2 },

  // level 3 — niche, opt-in
  { word: "Miso", hint: "fermented", level: 3 },
  { word: "Udon", hint: "slippery", level: 3 },
  { word: "Soba", hint: "nutty", level: 3 },
  { word: "Kimchi", hint: "pickled", level: 3 },
  { word: "Bibimbap", hint: "mixed", level: 3 },
  { word: "Dim Sum", hint: "plated", level: 3 },
  { word: "Wonton", hint: "floating", level: 3 },
  { word: "Pho", hint: "brothy", level: 3 },
  { word: "Satay", hint: "skewered", level: 3 },
  { word: "Mochi", hint: "pounded", level: 3 },
  { word: "Matcha", hint: "powdered", level: 3 },
  { word: "Gnocchi", hint: "pillowy", level: 3 },
  { word: "Polenta", hint: "gritty", level: 3 },
  { word: "Bruschetta", hint: "toasted", level: 3 },
  { word: "Cannoli", hint: "tubular", level: 3 },
  { word: "Tagine", hint: "conical", level: 3 },
  { word: "Baklava", hint: "honeyed", level: 3 },
  { word: "Halloumi", hint: "squeaky", level: 3 },
  { word: "Camembert", hint: "boxed", level: 3 },
  { word: "Ricotta", hint: "curdled", level: 3 },
  { word: "Prosciutto", hint: "translucent", level: 3 },
  { word: "Pastrami", hint: "peppery", level: 3 },
  { word: "Caviar", hint: "costly", level: 3 },
  { word: "Biryani", hint: "perfumed", level: 3 },
  { word: "Tahini", hint: "runny", level: 3 },
  { word: "Harissa", hint: "smouldering", level: 3 },
  { word: "Chutney", hint: "chunky", level: 3 },
  { word: "Saffron", hint: "precious", level: 3 },
  { word: "Cardamom", hint: "resinous", level: 3 },
  { word: "Nutmeg", hint: "woody", level: 3 },
  { word: "Macaron", hint: "pastel", level: 3 },
  { word: "Eclair", hint: "elongated", level: 3 },
  { word: "Creme Brulee", hint: "cracked", level: 3 },
  { word: "Panna Cotta", hint: "wobbly", level: 3 },
  { word: "Kombucha", hint: "tart", level: 3 },
  { word: "Sake", hint: "warmed", level: 3 },
  { word: "Mead", hint: "ancient", level: 3 },
  { word: "Sangria", hint: "fruity", level: 3 },
  { word: "Absinthe", hint: "potent", level: 3 },
  { word: "Prosecco", hint: "bubbly", level: 3 },
];
