import type { WordEntry } from "../types.js";

/**
 * Food & Drink, 200 entries: 70 at level 1, 90 at level 2, 40 at level 3.
 * Hints describe shape, texture and ritual only — never the identity, never
 * the category. Raw animal names are left to the Animals category; the only
 * claims here are prepared items ("Bacon", "Fried Chicken", "Fish and Chips").
 */
export const foodAndDrink: readonly WordEntry[] = [
  // level 1 — universally known
  { word: "Pizza", hint: "shared, round, often delivered", level: 1 },
  { word: "Burger", hint: "stacked, round bun, fast counter", level: 1 },
  { word: "Chocolate", hint: "sweet, dark, melts in hands", level: 1 },
  { word: "Ice Cream", hint: "frozen, scooped, drips quickly", level: 1 },
  { word: "Bread", hint: "sliced, plain, everyday staple", level: 1 },
  { word: "Cheese", hint: "aged, yellow, sliced or grated", level: 1 },
  { word: "Rice", hint: "white, plain, boiled in water", level: 1 },
  { word: "Spaghetti", hint: "twirled, boiled, tomato sauce", level: 1 },
  { word: "Noodles", hint: "long, slippery, in broth", level: 1 },
  { word: "Coffee", hint: "dark, bitter, morning ritual", level: 1 },
  { word: "Tea", hint: "hot, steeped, calming", level: 1 },
  { word: "Milk", hint: "white, cold, poured", level: 1 },
  { word: "Egg", hint: "oval, fragile, cracked open", level: 1 },
  { word: "Apple", hint: "crisp, round, red or green", level: 1 },
  { word: "Banana", hint: "curved, yellow, peeled", level: 1 },
  { word: "Orange", hint: "round, segmented, bright peel", level: 1 },
  { word: "Strawberry", hint: "small, red, seeds outside", level: 1 },
  { word: "Grape", hint: "small, round, grows in bunches", level: 1 },
  { word: "Watermelon", hint: "huge, striped, sliced in wedges", level: 1 },
  { word: "Lemon", hint: "sharp, yellow, squeezed", level: 1 },
  { word: "Potato", hint: "earthy, starchy, boiled or mashed", level: 1 },
  { word: "Tomato", hint: "round, red, soft and juicy", level: 1 },
  { word: "Carrot", hint: "long, orange, crunchy root", level: 1 },
  { word: "Onion", hint: "layered, pungent, brings tears", level: 1 },
  { word: "Salad", hint: "cold, tossed, green and light", level: 1 },
  { word: "Soup", hint: "hot, thin, in a bowl", level: 1 },
  { word: "Sandwich", hint: "two slices, filled, portable", level: 1 },
  { word: "Butter", hint: "pale yellow, soft, spread thickly", level: 1 },
  { word: "Sugar", hint: "white, fine, very sweet", level: 1 },
  { word: "Salt", hint: "white grains, sharp, sprinkled", level: 1 },
  { word: "Honey", hint: "golden, thick, from bees", level: 1 },
  { word: "Jam", hint: "sweet, sticky, in jars", level: 1 },
  { word: "Cake", hint: "layered, iced, birthday centrepiece", level: 1 },
  { word: "Cookie", hint: "small, round, crumbly", level: 1 },
  { word: "Doughnut", hint: "ring-shaped, glazed, fried", level: 1 },
  { word: "Pancake", hint: "flat, round, flipped", level: 1 },
  { word: "Waffle", hint: "square, crisp, patterned grid", level: 1 },
  { word: "Popcorn", hint: "light, puffed, sold at cinemas", level: 1 },
  { word: "French Fries", hint: "thin, salted, golden sticks", level: 1 },
  { word: "Ketchup", hint: "red, thick, squeezed out", level: 1 },
  { word: "Mustard", hint: "yellow, sharp, spread thinly", level: 1 },
  { word: "Mayonnaise", hint: "pale, thick, creamy spread", level: 1 },
  { word: "Peanut Butter", hint: "thick, brown, hard to spread", level: 1 },
  { word: "Cereal", hint: "dry, crunchy, with milk", level: 1 },
  { word: "Yogurt", hint: "thick, tangy, cultured", level: 1 },
  { word: "Hot Dog", hint: "long bun, street cart, mustard", level: 1 },
  { word: "Taco", hint: "folded, crisp shell, filled", level: 1 },
  { word: "Burrito", hint: "rolled, wrapped tight, heavy", level: 1 },
  { word: "Steak", hint: "thick cut, grilled, seared", level: 1 },
  { word: "Bacon", hint: "salty strips, fried, smoky", level: 1 },
  { word: "Sausage", hint: "cylindrical, grilled, in casing", level: 1 },
  { word: "Ham", hint: "pink, cured, in thin slices", level: 1 },
  { word: "Toast", hint: "warm, browned, crunchy slice", level: 1 },
  { word: "Juice", hint: "cold, sweet, sold in cartons", level: 1 },
  { word: "Soda", hint: "fizzy, sweet, canned", level: 1 },
  { word: "Beer", hint: "cold, bitter, foamy head", level: 1 },
  { word: "Wine", hint: "bottled, aged, red or white", level: 1 },
  { word: "Espresso", hint: "small, bitter, quick", level: 1 },
  { word: "Pie", hint: "round, filled, crust on top", level: 1 },
  { word: "Cucumber", hint: "green, cool, crisp and mild", level: 1 },
  { word: "Peas", hint: "tiny green balls, sweet", level: 1 },
  { word: "Garlic", hint: "small bulb, sharp, lingers on breath", level: 1 },
  { word: "Pineapple", hint: "spiky outside, yellow inside", level: 1 },
  { word: "Mango", hint: "sweet, tropical, orange flesh", level: 1 },
  { word: "Peach", hint: "soft, fuzzy skin, sweet", level: 1 },
  { word: "Cherry", hint: "small, red, has a stone", level: 1 },
  { word: "Candy", hint: "small, sugary, wrapped", level: 1 },
  { word: "Pumpkin", hint: "large, orange, hollowed out", level: 1 },
  { word: "Sushi", hint: "cold, precise, in small pieces", level: 1 },
  { word: "Fried Chicken", hint: "crisp coating, greasy, in buckets", level: 1 },

  // level 2 — commonly known
  { word: "Muffin", hint: "small, domed, paper case", level: 2 },
  { word: "Croissant", hint: "flaky, curved, buttery layers", level: 2 },
  { word: "Baguette", hint: "long, crusty, snapped in half", level: 2 },
  { word: "Bagel", hint: "chewy ring, boiled then baked", level: 2 },
  { word: "Pretzel", hint: "knotted, salted, chewy", level: 2 },
  { word: "Scone", hint: "dry, crumbly, with jam", level: 2 },
  { word: "Brownie", hint: "dense, dark, chewy square", level: 2 },
  { word: "Toffee", hint: "hard, sticky, buttery brown", level: 2 },
  { word: "Caramel", hint: "golden, sticky, burnt sugar", level: 2 },
  { word: "Meringue", hint: "white, airy, whipped and baked", level: 2 },
  { word: "Tiramisu", hint: "layered, coffee-soaked, dusted cocoa", level: 2 },
  { word: "Custard", hint: "thick, yellow, poured warm", level: 2 },
  { word: "Crepe", hint: "thin, folded, filled and rolled", level: 2 },
  { word: "Churro", hint: "ridged, fried, dusted with sugar", level: 2 },
  { word: "Marshmallow", hint: "white, squishy, toasted on sticks", level: 2 },
  { word: "Avocado", hint: "green, buttery, large pit", level: 2 },
  { word: "Coconut", hint: "hairy shell, white inside", level: 2 },
  { word: "Pear", hint: "pale green, grainy, sweet", level: 2 },
  { word: "Blueberry", hint: "tiny, dark, sold in punnets", level: 2 },
  { word: "Raspberry", hint: "soft, red, hollow centre", level: 2 },
  { word: "Lime", hint: "small, green, very sharp", level: 2 },
  { word: "Plum", hint: "dark purple, smooth, stone inside", level: 2 },
  { word: "Fig", hint: "soft, sweet, full of seeds", level: 2 },
  { word: "Pomegranate", hint: "hard skin, red seeds, staining", level: 2 },
  { word: "Broccoli", hint: "green, tree-shaped, steamed", level: 2 },
  { word: "Lettuce", hint: "light green, leafy, crisp", level: 2 },
  { word: "Mushroom", hint: "soft cap, earthy, sliced", level: 2 },
  { word: "Celery", hint: "pale stalks, watery, crunchy", level: 2 },
  { word: "Spinach", hint: "dark leaves, wilts fast", level: 2 },
  { word: "Asparagus", hint: "green spears, tender tips", level: 2 },
  { word: "Eggplant", hint: "glossy purple, spongy inside", level: 2 },
  { word: "Bell Pepper", hint: "hollow, glossy, crunchy walls", level: 2 },
  { word: "Chilli", hint: "small, red, fierce heat", level: 2 },
  { word: "Beetroot", hint: "deep purple, earthy, stains hands", level: 2 },
  { word: "Almond", hint: "oval kernel, pale, mild crunch", level: 2 },
  { word: "Pistachio", hint: "green kernel, split shell, salted", level: 2 },
  { word: "Chickpeas", hint: "small, round, pale and firm", level: 2 },
  { word: "Tofu", hint: "pale block, soft, absorbs sauces", level: 2 },
  { word: "Cappuccino", hint: "milky, foamed, small cup", level: 2 },
  { word: "Latte", hint: "milky, mild, tall glass", level: 2 },
  { word: "Smoothie", hint: "blended, cold, thick and pink", level: 2 },
  { word: "Cider", hint: "fizzy, sharp, from apples", level: 2 },
  { word: "Champagne", hint: "pale, bubbly, celebratory", level: 2 },
  { word: "Whiskey", hint: "amber, strong, oak barrels", level: 2 },
  { word: "Vodka", hint: "clear, strong, almost odourless", level: 2 },
  { word: "Rum", hint: "dark, sweet, sailors' spirit", level: 2 },
  { word: "Gin", hint: "clear, sharp, botanical", level: 2 },
  { word: "Tequila", hint: "clear, harsh, with salt", level: 2 },
  { word: "Marmalade", hint: "bitter, orange, sticky preserve", level: 2 },
  { word: "Maple Syrup", hint: "dark, sticky, poured on pancakes", level: 2 },
  { word: "Soy Sauce", hint: "dark, salty, tiny bottles", level: 2 },
  { word: "Vinegar", hint: "sharp, clear, sour splash", level: 2 },
  { word: "Olive", hint: "small, salty, brine-cured", level: 2 },
  { word: "Pickle", hint: "sour, crunchy, from a jar", level: 2 },
  { word: "Cinnamon", hint: "warm brown spice, dusted", level: 2 },
  { word: "Vanilla", hint: "pale, fragrant, from pods", level: 2 },
  { word: "Ginger", hint: "knobbly root, hot, sharp", level: 2 },
  { word: "Basil", hint: "torn green leaves, sweet, aromatic", level: 2 },
  { word: "Mint", hint: "cool, green, fresh leaves", level: 2 },
  { word: "Pepperoni", hint: "spicy red discs, oily", level: 2 },
  { word: "Chorizo", hint: "red, cured, coarse and spicy", level: 2 },
  { word: "Meatball", hint: "round, browned, in sauce", level: 2 },
  { word: "Feta", hint: "white, crumbly, salty brine", level: 2 },
  { word: "Mozzarella", hint: "white, stretchy, barely salty", level: 2 },
  { word: "Parmesan", hint: "hard, grated, salty shards", level: 2 },
  { word: "Brie", hint: "soft rind, oozing, mild", level: 2 },
  { word: "Curry", hint: "thick, spicy sauce, with rice", level: 2 },
  { word: "Lasagna", hint: "layered, baked, cut in squares", level: 2 },
  { word: "Ravioli", hint: "stuffed, boiled, in sauce", level: 2 },
  { word: "Risotto", hint: "slow, stirred, creamy", level: 2 },
  { word: "Carbonara", hint: "silky, peppery, with bacon", level: 2 },
  { word: "Pesto", hint: "green, oily, ground basil", level: 2 },
  { word: "Paella", hint: "yellow, shared pan, saffron", level: 2 },
  { word: "Ramen", hint: "hot broth, coiled strands, egg", level: 2 },
  { word: "Dumpling", hint: "pinched, steamed, soft parcels", level: 2 },
  { word: "Spring Roll", hint: "thin crisp wrapper, tightly wound", level: 2 },
  { word: "Kebab", hint: "skewered, charred, late night", level: 2 },
  { word: "Falafel", hint: "fried balls, chickpea, herby", level: 2 },
  { word: "Hummus", hint: "beige, smooth, scooped with pita", level: 2 },
  { word: "Guacamole", hint: "green, mashed, lime and salt", level: 2 },
  { word: "Quesadilla", hint: "folded, grilled, cheese inside", level: 2 },
  { word: "Nachos", hint: "crisp triangles, melted cheese, shared", level: 2 },
  { word: "Pita", hint: "flat, round, opens into pocket", level: 2 },
  { word: "Naan", hint: "soft flatbread, blistered, torn", level: 2 },
  { word: "Samosa", hint: "triangular, crisp, spiced filling", level: 2 },
  { word: "Tempura", hint: "light batter, crisp, deep-fried", level: 2 },
  { word: "Omelette", hint: "folded, yellow, quick in a pan", level: 2 },
  {
    word: "Fish and Chips",
    hint: "battered, vinegary, wrapped in paper",
    level: 2,
  },
  { word: "Couscous", hint: "tiny pale grains, fluffy", level: 2 },
  { word: "Pad Thai", hint: "sticky noodles, peanuts, lime", level: 2 },

  // level 3 — niche, opt-in
  { word: "Miso", hint: "fermented paste, salty, brown", level: 3 },
  { word: "Udon", hint: "thick white strands, chewy", level: 3 },
  { word: "Soba", hint: "thin buckwheat strands, cold", level: 3 },
  { word: "Kimchi", hint: "fermented cabbage, sour, fiery", level: 3 },
  { word: "Bibimbap", hint: "mixed bowl, egg on top", level: 3 },
  { word: "Dim Sum", hint: "small plates, shared, steamed", level: 3 },
  { word: "Wonton", hint: "thin skin, filled, in broth", level: 3 },
  { word: "Pho", hint: "clear broth, herbs, thin noodles", level: 3 },
  { word: "Satay", hint: "small skewers, grilled, peanut sauce", level: 3 },
  { word: "Mochi", hint: "chewy, pounded rice, soft", level: 3 },
  { word: "Matcha", hint: "bright green powder, whisked, bitter", level: 3 },
  { word: "Gnocchi", hint: "small potato pillows, soft", level: 3 },
  { word: "Polenta", hint: "coarse, yellow, soft and thick", level: 3 },
  { word: "Bruschetta", hint: "grilled slice, tomato, garlic", level: 3 },
  { word: "Cannoli", hint: "crisp tube, sweet filling", level: 3 },
  { word: "Tagine", hint: "slow, spiced, conical clay pot", level: 3 },
  { word: "Baklava", hint: "layered pastry, honey-soaked, nutty", level: 3 },
  { word: "Halloumi", hint: "squeaky, salty, holds its shape", level: 3 },
  { word: "Camembert", hint: "soft, pungent, sold boxed", level: 3 },
  { word: "Ricotta", hint: "soft white curds, faintly sweet", level: 3 },
  { word: "Prosciutto", hint: "paper-thin, salty, cured pink", level: 3 },
  { word: "Pastrami", hint: "peppery crust, smoked, piled high", level: 3 },
  { word: "Caviar", hint: "tiny black pearls, salty, costly", level: 3 },
  { word: "Biryani", hint: "spiced rice, layered, fragrant", level: 3 },
  { word: "Tahini", hint: "pale sesame paste, bitter", level: 3 },
  { word: "Harissa", hint: "red chilli paste, fiery, smoky", level: 3 },
  { word: "Chutney", hint: "sweet, chunky, spiced and sour", level: 3 },
  { word: "Saffron", hint: "red threads, precious, golden stain", level: 3 },
  { word: "Cardamom", hint: "green pods, fragrant, sharp", level: 3 },
  { word: "Nutmeg", hint: "hard brown seed, grated, warm", level: 3 },
  { word: "Macaron", hint: "small, pastel, chewy middle", level: 3 },
  { word: "Eclair", hint: "long, filled, chocolate-topped", level: 3 },
  { word: "Creme Brulee", hint: "cracked sugar top, cold beneath", level: 3 },
  { word: "Panna Cotta", hint: "wobbly, set, palest white", level: 3 },
  { word: "Kombucha", hint: "fizzy, sour, fermented brew", level: 3 },
  { word: "Sake", hint: "clear, warm, from rice", level: 3 },
  { word: "Mead", hint: "honeyed, ancient, fermented", level: 3 },
  { word: "Sangria", hint: "red, fruity, with slices", level: 3 },
  { word: "Absinthe", hint: "green, bitter, very strong", level: 3 },
  { word: "Prosecco", hint: "pale, fizzy, poured at parties", level: 3 },
];
