import type { WordEntry } from "../types.js";

/**
 * Jobs, 200 entries: 70 at level 1, 90 at level 2, 40 at level 3.
 * Occupations only — tools of the trade belong to Objects and premises belong
 * to Places. Every hint is exactly one lowercase word, chosen from temperament,
 * setting, hours, dress, what the hands hold and who the person faces. It never
 * shares a stem with its own occupation, which rules out the obvious root in
 * almost every case ("bake", "plumb", "teach", "drive", "build"), and it never
 * uses job, work, career, profession or trade, any of which would leak the
 * category outright.
 * Food roles left free by Food & Drink are claimed here: Chef, Baker, Barista,
 * Butcher, Sommelier.
 */
export const jobs: readonly WordEntry[] = [
  // level 1 — universally known
  { word: "Teacher", hint: "patient", level: 1 },
  { word: "Doctor", hint: "reassuring", level: 1 },
  { word: "Nurse", hint: "attentive", level: 1 },
  { word: "Chef", hint: "sweltering", level: 1 },
  { word: "Baker", hint: "early", level: 1 },
  { word: "Barista", hint: "steamy", level: 1 },
  { word: "Butcher", hint: "aproned", level: 1 },
  { word: "Farmer", hint: "muddy", level: 1 },
  { word: "Police Officer", hint: "uniformed", level: 1 },
  { word: "Firefighter", hint: "smoky", level: 1 },
  { word: "Pilot", hint: "airborne", level: 1 },
  { word: "Soldier", hint: "drilled", level: 1 },
  { word: "Sailor", hint: "seafaring", level: 1 },
  { word: "Dentist", hint: "gloved", level: 1 },
  { word: "Lawyer", hint: "billable", level: 1 },
  { word: "Judge", hint: "robed", level: 1 },
  { word: "Plumber", hint: "kneeling", level: 1 },
  { word: "Electrician", hint: "insulated", level: 1 },
  { word: "Carpenter", hint: "sawdust", level: 1 },
  { word: "Mechanic", hint: "greasy", level: 1 },
  { word: "Cleaner", hint: "nightly", level: 1 },
  { word: "Waiter", hint: "tipped", level: 1 },
  { word: "Cashier", hint: "seated", level: 1 },
  { word: "Barber", hint: "chatty", level: 1 },
  { word: "Tailor", hint: "pinned", level: 1 },
  { word: "Gardener", hint: "seasonal", level: 1 },
  { word: "Builder", hint: "scaffolded", level: 1 },
  { word: "Driver", hint: "mirrors", level: 1 },
  { word: "Postman", hint: "satchel", level: 1 },
  { word: "Librarian", hint: "hushed", level: 1 },
  { word: "Journalist", hint: "inquisitive", level: 1 },
  { word: "Photographer", hint: "framing", level: 1 },
  { word: "Actor", hint: "rehearsed", level: 1 },
  { word: "Singer", hint: "vocal", level: 1 },
  { word: "Dancer", hint: "limber", level: 1 },
  { word: "Musician", hint: "rhythmic", level: 1 },
  { word: "Artist", hint: "bohemian", level: 1 },
  { word: "Writer", hint: "solitary", level: 1 },
  { word: "Scientist", hint: "empirical", level: 1 },
  { word: "Engineer", hint: "calculating", level: 1 },
  { word: "Architect", hint: "spatial", level: 1 },
  { word: "Accountant", hint: "meticulous", level: 1 },
  { word: "Banker", hint: "pinstriped", level: 1 },
  { word: "Receptionist", hint: "welcoming", level: 1 },
  { word: "Manager", hint: "meetings", level: 1 },
  { word: "Shopkeeper", hint: "counter", level: 1 },
  { word: "Coach", hint: "touchline", level: 1 },
  { word: "Referee", hint: "impartial", level: 1 },
  { word: "Athlete", hint: "sinewy", level: 1 },
  { word: "Footballer", hint: "grassy", level: 1 },
  { word: "Lifeguard", hint: "sunburnt", level: 1 },
  { word: "Veterinarian", hint: "kindly", level: 1 },
  { word: "Pharmacist", hint: "dispensing", level: 1 },
  { word: "Surgeon", hint: "precise", level: 1 },
  { word: "Midwife", hint: "unflappable", level: 1 },
  { word: "Paramedic", hint: "urgent", level: 1 },
  { word: "Psychologist", hint: "probing", level: 1 },
  { word: "Politician", hint: "evasive", level: 1 },
  { word: "Priest", hint: "devout", level: 1 },
  { word: "Astronaut", hint: "weightless", level: 1 },
  { word: "Detective", hint: "suspicious", level: 1 },
  { word: "Bartender", hint: "nocturnal", level: 1 },
  { word: "Model", hint: "photogenic", level: 1 },
  { word: "Comedian", hint: "timing", level: 1 },
  { word: "Magician", hint: "secretive", level: 1 },
  { word: "Clown", hint: "painted", level: 1 },
  { word: "Fisherman", hint: "briny", level: 1 },
  { word: "Miner", hint: "subterranean", level: 1 },
  { word: "Spy", hint: "clandestine", level: 1 },
  { word: "Boxer", hint: "bruised", level: 1 },

  // level 2 — commonly known
  { word: "Professor", hint: "tenured", level: 2 },
  { word: "Headmaster", hint: "assemblies", level: 2 },
  { word: "Driving Instructor", hint: "passenger", level: 2 },
  { word: "Personal Trainer", hint: "repetitions", level: 2 },
  { word: "Physiotherapist", hint: "stretching", level: 2 },
  { word: "Counsellor", hint: "confidential", level: 2 },
  { word: "Social Worker", hint: "caseload", level: 2 },
  { word: "Babysitter", hint: "evenings", level: 2 },
  { word: "Lab Technician", hint: "pipettes", level: 2 },
  { word: "Zookeeper", hint: "buckets", level: 2 },
  { word: "Beekeeper", hint: "unhurried", level: 2 },
  { word: "Shepherd", hint: "hillside", level: 2 },
  { word: "Cowboy", hint: "dusty", level: 2 },
  { word: "Forester", hint: "saplings", level: 2 },
  { word: "Lumberjack", hint: "brawny", level: 2 },
  { word: "Park Ranger", hint: "wilderness", level: 2 },
  { word: "Florist", hint: "thorns", level: 2 },
  { word: "Greengrocer", hint: "crates", level: 2 },
  { word: "Fishmonger", hint: "chilled", level: 2 },
  { word: "Brewer", hint: "yeasty", level: 2 },
  { word: "Winemaker", hint: "cellars", level: 2 },
  { word: "Caterer", hint: "trays", level: 2 },
  { word: "Bookseller", hint: "shelved", level: 2 },
  { word: "Travel Agent", hint: "brochures", level: 2 },
  { word: "Tour Guide", hint: "umbrella", level: 2 },
  { word: "Flight Attendant", hint: "trolley", level: 2 },
  { word: "Air Traffic Controller", hint: "headset", level: 2 },
  { word: "Captain", hint: "bridge", level: 2 },
  { word: "Courier", hint: "signature", level: 2 },
  { word: "Chauffeur", hint: "discreet", level: 2 },
  { word: "Security Guard", hint: "torch", level: 2 },
  { word: "Ticket Inspector", hint: "unwelcome", level: 2 },
  { word: "Bricklayer", hint: "mortar", level: 2 },
  { word: "Roofer", hint: "ladder", level: 2 },
  { word: "Plasterer", hint: "skimmed", level: 2 },
  { word: "Tiler", hint: "gritty", level: 2 },
  { word: "Welder", hint: "sparks", level: 2 },
  { word: "Decorator", hint: "rollers", level: 2 },
  { word: "Locksmith", hint: "picks", level: 2 },
  { word: "Blacksmith", hint: "anvil", level: 2 },
  { word: "Landlord", hint: "rent", level: 2 },
  { word: "Caretaker", hint: "keys", level: 2 },
  { word: "Chimney Sweep", hint: "soot", level: 2 },
  { word: "Cobbler", hint: "leather", level: 2 },
  { word: "Jeweller", hint: "loupe", level: 2 },
  { word: "Potter", hint: "earthy", level: 2 },
  { word: "Optician", hint: "frames", level: 2 },
  { word: "Graphic Designer", hint: "typefaces", level: 2 },
  { word: "Web Designer", hint: "layouts", level: 2 },
  { word: "Interior Designer", hint: "swatches", level: 2 },
  { word: "Fashion Designer", hint: "seasons", level: 2 },
  { word: "Programmer", hint: "debugging", level: 2 },
  { word: "Data Analyst", hint: "spreadsheets", level: 2 },
  { word: "Consultant", hint: "slides", level: 2 },
  { word: "Stockbroker", hint: "adrenaline", level: 2 },
  { word: "Estate Agent", hint: "glossy", level: 2 },
  { word: "Editor", hint: "ruthless", level: 2 },
  { word: "Poet", hint: "unpaid", level: 2 },
  { word: "Translator", hint: "bilingual", level: 2 },
  { word: "Historian", hint: "archives", level: 2 },
  { word: "Philosopher", hint: "abstract", level: 2 },
  { word: "Economist", hint: "forecasts", level: 2 },
  { word: "Mathematician", hint: "proofs", level: 2 },
  { word: "Physicist", hint: "particles", level: 2 },
  { word: "Biologist", hint: "microscope", level: 2 },
  { word: "Geologist", hint: "strata", level: 2 },
  { word: "Botanist", hint: "greenhouse", level: 2 },
  { word: "Astronomer", hint: "starlit", level: 2 },
  { word: "Archaeologist", hint: "trowel", level: 2 },
  { word: "Illustrator", hint: "inky", level: 2 },
  { word: "Animator", hint: "painstaking", level: 2 },
  { word: "Producer", hint: "credits", level: 2 },
  { word: "Film Director", hint: "megaphone", level: 2 },
  { word: "Newsreader", hint: "poised", level: 2 },
  { word: "Conductor", hint: "baton", level: 2 },
  { word: "Violinist", hint: "rosin", level: 2 },
  { word: "Pianist", hint: "arpeggios", level: 2 },
  { word: "Drummer", hint: "sticks", level: 2 },
  { word: "Busker", hint: "coins", level: 2 },
  { word: "Jockey", hint: "wiry", level: 2 },
  { word: "Golfer", hint: "swinging", level: 2 },
  { word: "Cyclist", hint: "tyres", level: 2 },
  { word: "Gymnast", hint: "chalky", level: 2 },
  { word: "Mayor", hint: "ribbons", level: 2 },
  { word: "Diplomat", hint: "embassies", level: 2 },
  { word: "Monk", hint: "silence", level: 2 },
  { word: "Nun", hint: "habit", level: 2 },
  { word: "Rabbi", hint: "scrolls", level: 2 },
  { word: "Diver", hint: "bubbles", level: 2 },
  { word: "Explorer", hint: "uncharted", level: 2 },

  // level 3 — niche, opt-in
  { word: "Actuary", hint: "cautious", level: 3 },
  { word: "Sommelier", hint: "swirling", level: 3 },
  { word: "Cartographer", hint: "projections", level: 3 },
  { word: "Falconer", hint: "windswept", level: 3 },
  { word: "Farrier", hint: "stooping", level: 3 },
  { word: "Luthier", hint: "varnish", level: 3 },
  { word: "Piano Tuner", hint: "listening", level: 3 },
  { word: "Glassblower", hint: "furnace", level: 3 },
  { word: "Calligrapher", hint: "strokes", level: 3 },
  { word: "Bookbinder", hint: "stitched", level: 3 },
  { word: "Milliner", hint: "feathered", level: 3 },
  { word: "Upholsterer", hint: "staples", level: 3 },
  { word: "Glazier", hint: "putty", level: 3 },
  { word: "Toolmaker", hint: "thousandths", level: 3 },
  { word: "Draughtsman", hint: "pencilled", level: 3 },
  { word: "Town Planner", hint: "civic", level: 3 },
  { word: "Signwriter", hint: "lettered", level: 3 },
  { word: "Notary", hint: "seals", level: 3 },
  { word: "Paralegal", hint: "precedents", level: 3 },
  { word: "Archivist", hint: "boxes", level: 3 },
  { word: "Theologian", hint: "doctrinal", level: 3 },
  { word: "Columnist", hint: "byline", level: 3 },
  { word: "Proofreader", hint: "commas", level: 3 },
  { word: "Choreographer", hint: "sequenced", level: 3 },
  { word: "Puppeteer", hint: "strings", level: 3 },
  { word: "Ventriloquist", hint: "dummy", level: 3 },
  { word: "Roadie", hint: "cables", level: 3 },
  { word: "Cellist", hint: "resonant", level: 3 },
  { word: "Ornithologist", hint: "binoculars", level: 3 },
  { word: "Entomologist", hint: "specimens", level: 3 },
  { word: "Palaeontologist", hint: "fossilised", level: 3 },
  { word: "Anthropologist", hint: "kinship", level: 3 },
  { word: "Seismologist", hint: "tremors", level: 3 },
  { word: "Oceanographer", hint: "buoys", level: 3 },
  { word: "Statistician", hint: "confidence", level: 3 },
  { word: "Radiographer", hint: "shielded", level: 3 },
  { word: "Anaesthetist", hint: "backwards", level: 3 },
  { word: "Audiologist", hint: "soundproof", level: 3 },
  { word: "Acupuncturist", hint: "needles", level: 3 },
  { word: "Horticulturist", hint: "grafting", level: 3 },
];
