import type { WordEntry } from "../types.js";

/**
 * Objects, 200 entries: 70 at level 1, 90 at level 2, 40 at level 3.
 * Household, handheld and manufactured things. Every hint is exactly ONE
 * lowercase word describing material, weight, finish, sound or how the thing
 * is held — never the identity, never the category, and never sharing a stem
 * with its own word. Utensils and containers are claimed here ("Kettle",
 * "Mug", "Plate", "Chopsticks") as are the tools of every trade ("Hammer",
 * "Stethoscope", "Paintbrush"); Jobs keeps the occupations. Confusable pairs
 * are resolved to one side only: Sofa (not Couch), Mug (not Cup), Bag (not
 * Sack), Torch (not Flashlight), Rug (not Carpet), Jar (not Jug), Spanner
 * (not Wrench), Spade (not Shovel), Padlock (not Lock), Sink (not Basin),
 * Glasses (not Sunglasses), Pillow (not Cushion), Book (not Notebook).
 */
export const objects: readonly WordEntry[] = [
  // level 1 — universally known
  { word: "Chair", hint: "upholstered", level: 1 },
  { word: "Table", hint: "freestanding", level: 1 },
  { word: "Bed", hint: "restful", level: 1 },
  { word: "Sofa", hint: "cushioned", level: 1 },
  { word: "Door", hint: "threshold", level: 1 },
  { word: "Window", hint: "latched", level: 1 },
  { word: "Mirror", hint: "framed", level: 1 },
  { word: "Clock", hint: "ticking", level: 1 },
  { word: "Lamp", hint: "shaded", level: 1 },
  { word: "Candle", hint: "waxen", level: 1 },
  { word: "Pillow", hint: "plump", level: 1 },
  { word: "Blanket", hint: "woollen", level: 1 },
  { word: "Towel", hint: "damp", level: 1 },
  { word: "Soap", hint: "slippery", level: 1 },
  { word: "Toothbrush", hint: "bristled", level: 1 },
  { word: "Comb", hint: "toothed", level: 1 },
  { word: "Umbrella", hint: "collapsible", level: 1 },
  { word: "Hat", hint: "brimmed", level: 1 },
  { word: "Shoe", hint: "laced", level: 1 },
  { word: "Sock", hint: "knitted", level: 1 },
  { word: "Shirt", hint: "collared", level: 1 },
  { word: "Jacket", hint: "zipped", level: 1 },
  { word: "Belt", hint: "buckled", level: 1 },
  { word: "Glove", hint: "snug", level: 1 },
  { word: "Scarf", hint: "wrapped", level: 1 },
  { word: "Pencil", hint: "sharpened", level: 1 },
  { word: "Pen", hint: "capped", level: 1 },
  { word: "Book", hint: "bound", level: 1 },
  { word: "Scissors", hint: "bladed", level: 1 },
  { word: "Bag", hint: "roomy", level: 1 },
  { word: "Box", hint: "cardboard", level: 1 },
  { word: "Basket", hint: "wicker", level: 1 },
  { word: "Bucket", hint: "brimming", level: 1 },
  { word: "Broom", hint: "sweeping", level: 1 },
  { word: "Ladder", hint: "leaning", level: 1 },
  { word: "Hammer", hint: "blunt", level: 1 },
  { word: "Rope", hint: "coiled", level: 1 },
  { word: "Key", hint: "notched", level: 1 },
  { word: "Wallet", hint: "folded", level: 1 },
  { word: "Coin", hint: "jingling", level: 1 },
  { word: "Ring", hint: "golden", level: 1 },
  { word: "Watch", hint: "strapped", level: 1 },
  { word: "Glasses", hint: "perched", level: 1 },
  { word: "Phone", hint: "pocketable", level: 1 },
  { word: "Camera", hint: "snapping", level: 1 },
  { word: "Television", hint: "flickering", level: 1 },
  { word: "Radio", hint: "tuned", level: 1 },
  { word: "Computer", hint: "whirring", level: 1 },
  { word: "Battery", hint: "rechargeable", level: 1 },
  { word: "Torch", hint: "beaming", level: 1 },
  { word: "Fridge", hint: "humming", level: 1 },
  { word: "Oven", hint: "roasting", level: 1 },
  { word: "Kettle", hint: "boiling", level: 1 },
  { word: "Mug", hint: "ceramic", level: 1 },
  { word: "Plate", hint: "stacked", level: 1 },
  { word: "Bowl", hint: "concave", level: 1 },
  { word: "Spoon", hint: "scooping", level: 1 },
  { word: "Fork", hint: "pronged", level: 1 },
  { word: "Knife", hint: "serrated", level: 1 },
  { word: "Bottle", hint: "corked", level: 1 },
  { word: "Bicycle", hint: "pedalled", level: 1 },
  { word: "Car", hint: "parked", level: 1 },
  { word: "Bus", hint: "crowded", level: 1 },
  { word: "Train", hint: "rattling", level: 1 },
  { word: "Boat", hint: "floating", level: 1 },
  { word: "Ball", hint: "bouncy", level: 1 },
  { word: "Balloon", hint: "inflatable", level: 1 },
  { word: "Guitar", hint: "strummed", level: 1 },
  { word: "Drum", hint: "hollow", level: 1 },
  { word: "Piano", hint: "cumbersome", level: 1 },

  // level 2 — commonly known
  { word: "Trousers", hint: "creased", level: 2 },
  { word: "Necklace", hint: "clasped", level: 2 },
  { word: "Zip", hint: "toothy", level: 2 },
  { word: "Button", hint: "sewn", level: 2 },
  { word: "Needle", hint: "threading", level: 2 },
  { word: "Coat Hanger", hint: "wiry", level: 2 },
  { word: "Helmet", hint: "protective", level: 2 },
  { word: "Backpack", hint: "shouldered", level: 2 },
  { word: "Suitcase", hint: "wheeled", level: 2 },
  { word: "Passport", hint: "official", level: 2 },
  { word: "Ticket", hint: "torn", level: 2 },
  { word: "Map", hint: "unfolding", level: 2 },
  { word: "Calendar", hint: "gridded", level: 2 },
  { word: "Diary", hint: "private", level: 2 },
  { word: "Envelope", hint: "gummed", level: 2 },
  { word: "Stamp", hint: "perforated", level: 2 },
  { word: "Newspaper", hint: "inky", level: 2 },
  { word: "Eraser", hint: "rubbery", level: 2 },
  { word: "Ruler", hint: "graduated", level: 2 },
  { word: "Stapler", hint: "sprung", level: 2 },
  { word: "Calculator", hint: "numeric", level: 2 },
  { word: "Keyboard", hint: "clattering", level: 2 },
  { word: "Headphones", hint: "padded", level: 2 },
  { word: "Remote Control", hint: "handheld", level: 2 },
  { word: "Light Bulb", hint: "glowing", level: 2 },
  { word: "Plug", hint: "pinned", level: 2 },
  { word: "Fan", hint: "oscillating", level: 2 },
  { word: "Toaster", hint: "slotted", level: 2 },
  { word: "Microwave", hint: "beeping", level: 2 },
  { word: "Blender", hint: "whizzing", level: 2 },
  { word: "Washing Machine", hint: "sudsy", level: 2 },
  { word: "Vacuum Cleaner", hint: "roaring", level: 2 },
  { word: "Iron", hint: "scorching", level: 2 },
  { word: "Teapot", hint: "spouted", level: 2 },
  { word: "Frying Pan", hint: "sizzling", level: 2 },
  { word: "Chopping Board", hint: "scarred", level: 2 },
  { word: "Rolling Pin", hint: "cylindrical", level: 2 },
  { word: "Whisk", hint: "looped", level: 2 },
  { word: "Grater", hint: "abrasive", level: 2 },
  { word: "Corkscrew", hint: "spiral", level: 2 },
  { word: "Chopsticks", hint: "paired", level: 2 },
  { word: "Jar", hint: "lidded", level: 2 },
  { word: "Straw", hint: "sipped", level: 2 },
  { word: "Napkin", hint: "starched", level: 2 },
  { word: "Sink", hint: "plumbed", level: 2 },
  { word: "Tap", hint: "dripping", level: 2 },
  { word: "Bathtub", hint: "enamelled", level: 2 },
  { word: "Sponge", hint: "porous", level: 2 },
  { word: "Mop", hint: "sodden", level: 2 },
  { word: "Bin", hint: "smelly", level: 2 },
  { word: "Toothpaste", hint: "minty", level: 2 },
  { word: "Razor", hint: "honed", level: 2 },
  { word: "Hairdryer", hint: "blustery", level: 2 },
  { word: "Tweezers", hint: "pinching", level: 2 },
  { word: "Thermometer", hint: "calibrated", level: 2 },
  { word: "Stethoscope", hint: "listening", level: 2 },
  { word: "Wheelchair", hint: "pushed", level: 2 },
  { word: "Screwdriver", hint: "twisting", level: 2 },
  { word: "Spanner", hint: "jawed", level: 2 },
  { word: "Pliers", hint: "gripping", level: 2 },
  { word: "Drill", hint: "boring", level: 2 },
  { word: "Saw", hint: "rasping", level: 2 },
  { word: "Paintbrush", hint: "bristly", level: 2 },
  { word: "Padlock", hint: "shackled", level: 2 },
  { word: "Wheelbarrow", hint: "tipping", level: 2 },
  { word: "Watering Can", hint: "tilted", level: 2 },
  { word: "Spade", hint: "digging", level: 2 },
  { word: "Lawnmower", hint: "chugging", level: 2 },
  { word: "Desk", hint: "cluttered", level: 2 },
  { word: "Wardrobe", hint: "capacious", level: 2 },
  { word: "Shelf", hint: "mounted", level: 2 },
  { word: "Bench", hint: "slatted", level: 2 },
  { word: "Mattress", hint: "quilted", level: 2 },
  { word: "Rug", hint: "woven", level: 2 },
  { word: "Curtain", hint: "billowing", level: 2 },
  { word: "Vase", hint: "slender", level: 2 },
  { word: "Compass", hint: "magnetic", level: 2 },
  { word: "Binoculars", hint: "twinned", level: 2 },
  { word: "Telescope", hint: "skyward", level: 2 },
  { word: "Flag", hint: "fluttering", level: 2 },
  { word: "Whistle", hint: "shrill", level: 2 },
  { word: "Kite", hint: "soaring", level: 2 },
  { word: "Violin", hint: "bowed", level: 2 },
  { word: "Trumpet", hint: "brassy", level: 2 },
  { word: "Skateboard", hint: "trundling", level: 2 },
  { word: "Dice", hint: "tumbling", level: 2 },
  { word: "Teddy Bear", hint: "cuddly", level: 2 },
  { word: "Tent", hint: "pegged", level: 2 },
  { word: "Motorcycle", hint: "throaty", level: 2 },
  { word: "Aeroplane", hint: "airborne", level: 2 },

  // level 3 — niche, opt-in
  { word: "Theodolite", hint: "tripod", level: 3 },
  { word: "Sextant", hint: "nautical", level: 3 },
  { word: "Astrolabe", hint: "celestial", level: 3 },
  { word: "Abacus", hint: "sliding", level: 3 },
  { word: "Sundial", hint: "shadowed", level: 3 },
  { word: "Hourglass", hint: "trickling", level: 3 },
  { word: "Barometer", hint: "atmospheric", level: 3 },
  { word: "Protractor", hint: "angular", level: 3 },
  { word: "Slide Rule", hint: "obsolete", level: 3 },
  { word: "Anvil", hint: "forged", level: 3 },
  { word: "Bellows", hint: "pumping", level: 3 },
  { word: "Awl", hint: "piercing", level: 3 },
  { word: "Mallet", hint: "wooden", level: 3 },
  { word: "Crowbar", hint: "prising", level: 3 },
  { word: "Chisel", hint: "paring", level: 3 },
  { word: "Scythe", hint: "reaping", level: 3 },
  { word: "Sickle", hint: "curved", level: 3 },
  { word: "Pitchfork", hint: "tined", level: 3 },
  { word: "Kiln", hint: "firing", level: 3 },
  { word: "Lathe", hint: "turning", level: 3 },
  { word: "Loom", hint: "warped", level: 3 },
  { word: "Spinning Wheel", hint: "treadled", level: 3 },
  { word: "Thimble", hint: "dimpled", level: 3 },
  { word: "Crochet Hook", hint: "barbed", level: 3 },
  { word: "Pestle", hint: "grinding", level: 3 },
  { word: "Decanter", hint: "crystalline", level: 3 },
  { word: "Samovar", hint: "steaming", level: 3 },
  { word: "Tureen", hint: "communal", level: 3 },
  { word: "Cafetiere", hint: "plunging", level: 3 },
  { word: "Trivet", hint: "footed", level: 3 },
  { word: "Metronome", hint: "insistent", level: 3 },
  { word: "Harpsichord", hint: "plucked", level: 3 },
  { word: "Bagpipes", hint: "droning", level: 3 },
  { word: "Sitar", hint: "resonant", level: 3 },
  { word: "Gramophone", hint: "crackling", level: 3 },
  { word: "Typewriter", hint: "clacking", level: 3 },
  { word: "Quill", hint: "feathered", level: 3 },
  { word: "Monocle", hint: "single", level: 3 },
  { word: "Cravat", hint: "silken", level: 3 },
  { word: "Kaleidoscope", hint: "shifting", level: 3 },
];
