import type { WordEntry } from "../types.js";

/**
 * Places, 200 entries: 70 at level 1, 90 at level 2, 40 at level 3.
 * Every hint is exactly one lowercase word, unique within the category, and
 * shares no stem with its own word. Hints name texture, climate, scale,
 * sound, material or mood — never the identity, and never the words
 * place/location/city/town/country/region, which would leak the category.
 * 135 entries are generic place-types and 65 are named (10 at level 1, 30 at
 * level 2, 25 at level 3), so the default level 1 + level 2 pool stays
 * describable by a player with no geography. Venues left by Food & Drink are
 * claimed here (Bakery, Cafe, Restaurant, Brewery, Vineyard); occupations
 * belong to Jobs and household things to Objects.
 */
export const places: readonly WordEntry[] = [
  // level 1 — universally known
  { word: "Beach", hint: "sandy", level: 1 },
  { word: "Ocean", hint: "vast", level: 1 },
  { word: "Island", hint: "isolated", level: 1 },
  { word: "Mountain", hint: "steep", level: 1 },
  { word: "Hill", hint: "rounded", level: 1 },
  { word: "Valley", hint: "sheltered", level: 1 },
  { word: "Cliff", hint: "sheer", level: 1 },
  { word: "Cave", hint: "echoing", level: 1 },
  { word: "Volcano", hint: "molten", level: 1 },
  { word: "River", hint: "flowing", level: 1 },
  { word: "Lake", hint: "still", level: 1 },
  { word: "Waterfall", hint: "roaring", level: 1 },
  { word: "Forest", hint: "shaded", level: 1 },
  { word: "Jungle", hint: "humid", level: 1 },
  { word: "Desert", hint: "arid", level: 1 },
  { word: "Field", hint: "fenced", level: 1 },
  { word: "Countryside", hint: "unhurried", level: 1 },
  { word: "Moon", hint: "cratered", level: 1 },
  { word: "Park", hint: "grassy", level: 1 },
  { word: "Garden", hint: "planted", level: 1 },
  { word: "Playground", hint: "boisterous", level: 1 },
  { word: "Pyramid", hint: "ancient", level: 1 },
  { word: "School", hint: "noisy", level: 1 },
  { word: "University", hint: "studious", level: 1 },
  { word: "Library", hint: "quiet", level: 1 },
  { word: "Museum", hint: "hushed", level: 1 },
  { word: "Art Gallery", hint: "curated", level: 1 },
  { word: "Hospital", hint: "sterile", level: 1 },
  { word: "Office", hint: "fluorescent", level: 1 },
  { word: "Factory", hint: "industrial", level: 1 },
  { word: "Shop", hint: "stocked", level: 1 },
  { word: "Supermarket", hint: "queued", level: 1 },
  { word: "Bakery", hint: "floury", level: 1 },
  { word: "Cafe", hint: "chatty", level: 1 },
  { word: "Restaurant", hint: "candlelit", level: 1 },
  { word: "Pub", hint: "boozy", level: 1 },
  { word: "Hotel", hint: "booked", level: 1 },
  { word: "Cinema", hint: "darkened", level: 1 },
  { word: "Theatre", hint: "curtained", level: 1 },
  { word: "Stadium", hint: "packed", level: 1 },
  { word: "Gym", hint: "sweaty", level: 1 },
  { word: "Swimming Pool", hint: "chlorinated", level: 1 },
  { word: "Zoo", hint: "caged", level: 1 },
  { word: "Farm", hint: "muddy", level: 1 },
  { word: "Barn", hint: "dusty", level: 1 },
  { word: "Campsite", hint: "pitched", level: 1 },
  { word: "Village", hint: "sleepy", level: 1 },
  { word: "Street", hint: "paved", level: 1 },
  { word: "Motorway", hint: "tarmac", level: 1 },
  { word: "Bridge", hint: "arched", level: 1 },
  { word: "Tunnel", hint: "drilled", level: 1 },
  { word: "Bus Stop", hint: "timetabled", level: 1 },
  { word: "Train Station", hint: "departures", level: 1 },
  { word: "Airport", hint: "luggage", level: 1 },
  { word: "Harbour", hint: "moored", level: 1 },
  { word: "Church", hint: "solemn", level: 1 },
  { word: "Cathedral", hint: "vaulted", level: 1 },
  { word: "Castle", hint: "fortified", level: 1 },
  { word: "Palace", hint: "gilded", level: 1 },
  { word: "Tower", hint: "tall", level: 1 },
  { word: "Paris", hint: "romantic", level: 1 },
  { word: "London", hint: "rainy", level: 1 },
  { word: "Rome", hint: "imperial", level: 1 },
  { word: "New York", hint: "restless", level: 1 },
  { word: "Egypt", hint: "dynastic", level: 1 },
  { word: "Japan", hint: "orderly", level: 1 },
  { word: "China", hint: "populous", level: 1 },
  { word: "Italy", hint: "sunlit", level: 1 },
  { word: "India", hint: "spiced", level: 1 },
  { word: "Australia", hint: "sunburnt", level: 1 },

  // level 2 — commonly known
  { word: "Glacier", hint: "creeping", level: 2 },
  { word: "Iceberg", hint: "floating", level: 2 },
  { word: "Canyon", hint: "carved", level: 2 },
  { word: "Crater", hint: "hollowed", level: 2 },
  { word: "Coral Reef", hint: "shallow", level: 2 },
  { word: "Dune", hint: "shifting", level: 2 },
  { word: "Savannah", hint: "grazed", level: 2 },
  { word: "Swamp", hint: "murky", level: 2 },
  { word: "Peninsula", hint: "jutting", level: 2 },
  { word: "Bay", hint: "curved", level: 2 },
  { word: "Coast", hint: "salty", level: 2 },
  { word: "Highlands", hint: "windswept", level: 2 },
  { word: "Wilderness", hint: "trackless", level: 2 },
  { word: "Pier", hint: "planked", level: 2 },
  { word: "Lighthouse", hint: "striped", level: 2 },
  { word: "Windmill", hint: "turning", level: 2 },
  { word: "Vineyard", hint: "sloped", level: 2 },
  { word: "Brewery", hint: "hoppy", level: 2 },
  { word: "Orchard", hint: "laden", level: 2 },
  { word: "Greenhouse", hint: "muggy", level: 2 },
  { word: "Plantation", hint: "harvested", level: 2 },
  { word: "Reservoir", hint: "brimming", level: 2 },
  { word: "Dam", hint: "concrete", level: 2 },
  { word: "Canal", hint: "barges", level: 2 },
  { word: "Mine", hint: "subterranean", level: 2 },
  { word: "Shipyard", hint: "welded", level: 2 },
  { word: "Silo", hint: "cylindrical", level: 2 },
  { word: "Warehouse", hint: "cavernous", level: 2 },
  { word: "Cellar", hint: "cool", level: 2 },
  { word: "Rooftop", hint: "exposed", level: 2 },
  { word: "Skyscraper", hint: "towering", level: 2 },
  { word: "Apartment", hint: "rented", level: 2 },
  { word: "Cottage", hint: "thatched", level: 2 },
  { word: "Hut", hint: "flimsy", level: 2 },
  { word: "Stable", hint: "straw", level: 2 },
  { word: "Suburb", hint: "identical", level: 2 },
  { word: "Roundabout", hint: "circular", level: 2 },
  { word: "Petrol Station", hint: "forecourt", level: 2 },
  { word: "Courthouse", hint: "sworn", level: 2 },
  { word: "Pharmacy", hint: "prescribed", level: 2 },
  { word: "Canteen", hint: "trays", level: 2 },
  { word: "Bazaar", hint: "haggling", level: 2 },
  { word: "Casino", hint: "windowless", level: 2 },
  { word: "Nightclub", hint: "thumping", level: 2 },
  { word: "Concert Hall", hint: "acoustic", level: 2 },
  { word: "Bowling Alley", hint: "pins", level: 2 },
  { word: "Aquarium", hint: "glassy", level: 2 },
  { word: "Funfair", hint: "garish", level: 2 },
  { word: "Racetrack", hint: "banked", level: 2 },
  { word: "Golf Course", hint: "mown", level: 2 },
  { word: "Tennis Court", hint: "netted", level: 2 },
  { word: "Ice Rink", hint: "gliding", level: 2 },
  { word: "Ski Slope", hint: "snowy", level: 2 },
  { word: "Spa", hint: "pampering", level: 2 },
  { word: "Sauna", hint: "steaming", level: 2 },
  { word: "Temple", hint: "incense", level: 2 },
  { word: "Mosque", hint: "carpeted", level: 2 },
  { word: "Ruins", hint: "crumbling", level: 2 },
  { word: "Monument", hint: "commemorative", level: 2 },
  { word: "Fountain", hint: "splashing", level: 2 },
  { word: "Tokyo", hint: "neon", level: 2 },
  { word: "Berlin", hint: "graffitied", level: 2 },
  { word: "Madrid", hint: "sunbaked", level: 2 },
  { word: "Barcelona", hint: "coastal", level: 2 },
  { word: "Amsterdam", hint: "bicycles", level: 2 },
  { word: "Venice", hint: "sinking", level: 2 },
  { word: "Moscow", hint: "freezing", level: 2 },
  { word: "Cairo", hint: "teeming", level: 2 },
  { word: "Athens", hint: "columned", level: 2 },
  { word: "Istanbul", hint: "domed", level: 2 },
  { word: "Dubai", hint: "opulent", level: 2 },
  { word: "Sydney", hint: "breezy", level: 2 },
  { word: "Rio de Janeiro", hint: "carnival", level: 2 },
  { word: "Mexico", hint: "vibrant", level: 2 },
  { word: "Brazil", hint: "tropical", level: 2 },
  { word: "Canada", hint: "forested", level: 2 },
  { word: "Iceland", hint: "volcanic", level: 2 },
  { word: "Norway", hint: "wintry", level: 2 },
  { word: "Greece", hint: "sunbleached", level: 2 },
  { word: "Peru", hint: "terraced", level: 2 },
  { word: "Mars", hint: "airless", level: 2 },
  { word: "Sahara", hint: "burning", level: 2 },
  { word: "Everest", hint: "highest", level: 2 },
  { word: "Himalayas", hint: "snowbound", level: 2 },
  { word: "Alps", hint: "jagged", level: 2 },
  { word: "Nile", hint: "flooding", level: 2 },
  { word: "Great Wall", hint: "defensive", level: 2 },
  { word: "Stonehenge", hint: "megalithic", level: 2 },
  { word: "Colosseum", hint: "tiered", level: 2 },
  { word: "Taj Mahal", hint: "marble", level: 2 },

  // level 3 — niche, opt-in
  { word: "Fjord", hint: "glacial", level: 3 },
  { word: "Atoll", hint: "encircling", level: 3 },
  { word: "Archipelago", hint: "scattered", level: 3 },
  { word: "Lagoon", hint: "enclosed", level: 3 },
  { word: "Estuary", hint: "brackish", level: 3 },
  { word: "Delta", hint: "silty", level: 3 },
  { word: "Oasis", hint: "verdant", level: 3 },
  { word: "Geyser", hint: "spouting", level: 3 },
  { word: "Plateau", hint: "elevated", level: 3 },
  { word: "Tundra", hint: "frozen", level: 3 },
  { word: "Steppe", hint: "treeless", level: 3 },
  { word: "Moor", hint: "boggy", level: 3 },
  { word: "Aqueduct", hint: "channelled", level: 3 },
  { word: "Monastery", hint: "cloistered", level: 3 },
  { word: "Observatory", hint: "starlit", level: 3 },
  { word: "Reykjavik", hint: "northerly", level: 3 },
  { word: "Ulaanbaatar", hint: "smoggy", level: 3 },
  { word: "Vladivostok", hint: "naval", level: 3 },
  { word: "Kathmandu", hint: "lofty", level: 3 },
  { word: "Marrakesh", hint: "souks", level: 3 },
  { word: "Samarkand", hint: "silken", level: 3 },
  { word: "Kyoto", hint: "traditional", level: 3 },
  { word: "Timbuktu", hint: "fabled", level: 3 },
  { word: "Zanzibar", hint: "dhows", level: 3 },
  { word: "Andalusia", hint: "whitewashed", level: 3 },
  { word: "Sicily", hint: "citrus", level: 3 },
  { word: "Lapland", hint: "reindeer", level: 3 },
  { word: "Siberia", hint: "permafrost", level: 3 },
  { word: "Patagonia", hint: "desolate", level: 3 },
  { word: "Namibia", hint: "parched", level: 3 },
  { word: "Mongolia", hint: "nomadic", level: 3 },
  { word: "Bhutan", hint: "mountainous", level: 3 },
  { word: "Tasmania", hint: "southern", level: 3 },
  { word: "Galapagos", hint: "equatorial", level: 3 },
  { word: "Serengeti", hint: "migratory", level: 3 },
  { word: "Kilimanjaro", hint: "snowcapped", level: 3 },
  { word: "Yucatan", hint: "limestone", level: 3 },
  { word: "Machu Picchu", hint: "abandoned", level: 3 },
  { word: "Angkor Wat", hint: "overgrown", level: 3 },
  { word: "Petra", hint: "chiselled", level: 3 },
];
